# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

_target_: "lm_eval.models.huggingface.AutoMaskedLM"
name: "roberta-base"
kwargs:
  pretrained: "FacebookAI/roberta-base"
  trust_remote_code: false
