# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

# @group multimodal
# DevBench Sem-VizObjCat Evaluation

defaults:
  - devbench
  - _self_

output_dir: "${oc.env:HOME}/egobabyvlm_experiments/evals"

_target_: "evaluation.multimodal.devbench.base.DevBenchSemVizObjCatEvalModule"

name: "sem-viz_obj_cat"

dataset:
  _target_: "evaluation.data.devbench.DevBenchDataset"
  name: "sem-viz_obj_cat"
  kwargs:
    dataset_folder: "${oc.env:DEVBENCH_DATA_ROOT}/sem-viz_obj_cat"

human_data_path: "${oc.env:DEVBENCH_DATA_ROOT}/sem-viz_obj_cat/human.rds"

model: ${model}

seed: 42
