# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

# @group vision
# Linear Probe ImageNet Evaluation

defaults:
  - linear
  - _self_

output_dir: "${oc.env:HOME}/egobabyvlm_experiments/evals"

train_dataset:
  _target_: "evaluation.data.abx.DinoImagenetClassificationDataset"
  name: "imagenet_train"
  kwargs:
    dataset_str: "ImageNet;split=TRAIN;root=${oc.env:IMAGENET_ROOT};extra=${oc.env:IMAGENET_EXTRA}"
    mode: "train"

val_dataset:
  _target_: "evaluation.data.abx.DinoImagenetClassificationDataset"
  name: "imagenet_val"
  kwargs:
    dataset_str: "ImageNet;split=VAL;root=${oc.env:IMAGENET_ROOT};extra=${oc.env:IMAGENET_EXTRA}"


pooling_strategies:
  - {pooling: "concat_cls", last_n_layers: 1}
  - {pooling: "concat_cls", last_n_layers: 4}
  - {pooling: "concat_cls_avgpool", last_n_layers: 1}
  - {pooling: "concat_cls_avgpool", last_n_layers: 4}

learning_rates: [1e-5, 2e-5, 5e-5, 1e-4, 2e-4, 5e-4, 1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2, 0.1, 0.2, 0.3, 0.5]

batch_size: 128
epochs: 10
epoch_length: 1250
num_workers: 12
eval_period_iterations: 1250
num_gpus: 8

seed: 42

model: ${model}
